csv output support
np-guard/netpol-analyzer pull request #117
Opened 2023-04-09 13:36 UTC by shireenf-ibm

2023-04-09 14:17 UTC, elevran requested changes

2023-04-09 14:17 UTC, elevran commented on cmd/netpolicy/cmd/command_test.go
> +default/checkoutservice[Deployment],default/emailservice[Deployment],TCP 8080
might be better with string addition, to retain indentation for multiline:
```go
   expectedOutput: "src,dst,conn\n"+
                   "default/checkoutservice[Deployment],default/emailservice[Deployment],TCP 8080\n"+
                   "default/emailservice[Deployment],default/emailservice[Deployment],All Connections\n"

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/connlist.go
> +var ValidFormats = []string{TxtFormat, JSONFormat, DotFormat, CsvFormat}
Should be `CSVFormat`, and `DOTFormat` same as `JSONFormat` - they're all acronyms. 
BTW - may want to use `TextFormat` explicitly

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/connlist_test.go
> +func TestWithCsvOutputFormat(t *testing.T) {
Up-case `CSV`?

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/connlist_test.go
> +	res, err1 := analyzer.ConnlistFromDirPath(dirPath)
might be ok to use `err` in all, with each new definition shadowing previous, instead of `err1`, `err2`, ...

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/conns_formatter.go
> +func writeConnsIntoSortedSingleConnFieldsArray(conns []Peer2PeerConnection) []singleConnFields {
The `write` verb does not reflect the actual operation done by the function. I think `sortConnections` may be more accurate

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/conns_formatter.go
> +type csvFormatter struct {
Since `CSV` is an acronym *and* there is no intention to export the struct, may want to rename it as `formatCSV`.
Similarly for other formats.

2023-04-09 14:17 UTC, elevran commented on pkg/netpol/connlist/conns_formatter.go
> +// returns a csv string form of connections from list of Peer2PeerConnection objects
upcase `CSV`

2023-04-09 19:27 UTC, shireenf-ibm commented on README.md
> +  -o, --output string       Required output format (txt, json, dot, csv) (default "txt")
it is used in the help string in `list.go`  as following:
```
// output format - default txt
supportedFormats := strings.Join(connlist.ValidFormats, ",")
listCmd.Flags().StringVarP(&output, "output", "o", connlist.DefaultFormat, "Required output format ("+supportedFormats+")")
```

may we use it in other places too?

2023-04-10 10:24 UTC, elevran approved these changes

2023-04-10 10:26 UTC, merged