adding fake ip for pod from core
np-guard/netpol-analyzer pull request #127
Opened 2023-05-01 08:01 UTC by shireenf-ibm

2023-05-01 09:12 UTC, adisos commented
please read this issue, as it is relevant: https://github.com/np-guard/netpol-analyzer/issues/44
does your change assign fake ip only to pods read from files?

2023-05-01 09:16 UTC, shireenf-ibm commented
> please read this issue, as it is relevant: #44 does your change assign fake ip only to pods read from files?

not sure, will re-check and update

2023-05-08 10:34 UTC, adisos requested changes

2023-05-08 10:43 UTC, shireenf-ibm commented on pkg/netpol/eval/internal/k8s/pod.go
> -	return ipv4LoopbackAddr
done

2023-05-08 10:43 UTC, shireenf-ibm commented on pkg/netpol/eval/internal/k8s/pod.go
> -		pod.HostIP = getFakePodIP()
done

2023-05-08 11:04 UTC, adisos commented on pkg/netpol/eval/internal/k8s/pod.go
> +	if p.Status.HostIP == "" && len(p.Status.PodIPs) == 0 { // not scheduled nor assigned IP addresses - ignore
`HostIP` is IP address of the host to which the pod is assigned. Empty if not yet scheduled.
`PodIPs` holds the IP addresses allocated to the pod. If this field is specified, the 0th entry must match the podIP field.(which is IP address allocated to the pod.Empty if not yet allocated.).

I think we need both. on a live cluster we should ignore such pods (if at least one condition holds).
Let's revert this change, and also add in the scanner a fake pod ip to `p.Status.PodIPs`.

2023-05-08 12:31 UTC, shireenf-ibm commented on pkg/netpol/eval/internal/k8s/pod.go
> +	if p.Status.HostIP == "" && len(p.Status.PodIPs) == 0 { // not scheduled nor assigned IP addresses - ignore
- Is assigning the fake ip to the `p.Status.PodIPs[0]` enough? should check if there is a` p.Status.PodIP`? 
- Is it okay to use same fake ip for both `p.Status.PodIPs[0] `and` p.Status.HostIP`?

2023-05-08 12:48 UTC, adisos commented on pkg/netpol/eval/internal/k8s/pod.go
> +	if p.Status.HostIP == "" && len(p.Status.PodIPs) == 0 { // not scheduled nor assigned IP addresses - ignore
- yes, and you should only check the slice `p.Status.PodIPs`.
- yes

2023-05-08 13:12 UTC, adisos commented on pkg/netpol/scan/scan.go
> +// IPv4LoopbackAddr is used as fake IP in the absenceof Pod.Status.HostIP or Pod.Status.PodIPs
```suggestion
// IPv4LoopbackAddr is used as fake IP in the absence of Pod.Status.HostIP or Pod.Status.PodIPs
```

2023-05-08 13:12 UTC, adisos commented on pkg/netpol/scan/scan.go
> +func checkAndUpdatePodStatusIPsFields(rc *v1.Pod) {
```suggestion
// checkAndUpdatePodStatusIPsFields adds fake IP to pod.Status.HostIP or pod.Status.PodIPs if missing
func checkAndUpdatePodStatusIPsFields(rc *v1.Pod) {
```

2023-05-08 20:13 UTC, adisos approved these changes

2023-05-09 06:01 UTC, merged