connlist output doc update
np-guard/netpol-analyzer pull request #284
Opened 2023-12-07 15:47 UTC by shireenf-ibm

#282

2023-12-10 06:53 UTC, adisos requested changes

2023-12-10 16:27 UTC, shireenf-ibm commented on docs/connlist_output.md
sure, shouldn't it be for `netpol-analysis-example-minimal` (the diff example is diff from this)/

2023-12-10 17:15 UTC, adisos commented on docs/connlist_output.md
right, yes

2023-12-11 09:26 UTC, shireenf-ibm commented on docs/connlist_output.md
done

2023-12-17 14:05 UTC, adisos commented on docs/connlist_output.md
> +```
```suggestion
dot -Tsvg test_outputs/connlist/netpol-analysis-example-minimal_connlist_output.dot -O
```
```

2023-12-17 19:57 UTC, adisos approved these changes

2023-12-18 07:05 UTC, merged